# fly.toml app configuration file generated for backend-patient-sun-andreas on 2025-06-09T12:54:39+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-patient-sun-andreas'
primary_region = 'fra'

[build]

[env]
  DATASOURCE_PASSWORD = 'VKPVT1UcVyBGBEIGqDgb'
  DATASOURCE_URL = 'jdbc:postgresql://database-1.cfymcuwwq9ty.eu-north-1.rds.amazonaws.com:5432/electricalDB'
  DATASOURCE_USER = 'postgres'
  FRONTEND_URL = 'https://electrical-management-tool-restfull.vercel.app'

[http_service]
  internal_port = 8181
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
